### ISSUE TITLE
Uncaught exception in server

### ISSUE THREAD

**Issue by AsturaPhoenix** [AsturaPhoenix/trip_planner_aquamarine#80]
This exception is eventually caught, but we probably don't register an error handler early enough for Dart to consider the error caught. This is probably a future in a cache. The traces weren't particularly useful; one instance was an `http.ClientException` from `interleave2x32`.

In the error logs:
```
[2023-07-30 01:40:03.554665Z] WARNING AquamarineServer: Failed to fetch f025.20230729.t21z
        Connection closed while receiving data
#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:82:13)
#1      Stream.handleError.<anonymous closure> (dart:async/stream.dart:923:16)
```

This probably only impacts running in debug mode, where the VM stops on uncaught exceptions.

**Comment by AsturaPhoenix** [comment]
This is probably spurious. Tests of this test case do not complain of an uncaught exception unless observatory is attached, so this is likely  related to https://github.com/dart-lang/sdk/issues/47985 and friends. That is to say, the uncaught exception handler for the test zone is never invoked; only the debugger complains. I suspect the latter is using less robust/correct logic to determine whether an exception is caught.

Will close this issue after committing a test.
